name: upper-build


on:
    push:
        paths:
            - '.github/workflows/upper-build.yml'
            - 'demo-files/upper/**'
    workflow_dispatch: # manual

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # use the actions/checkout@v2 action to checkout the repository
            - run: pwd && ls -la
            - name: Checkout repository
              uses: actions/checkout@v2
            - run: pwd && ls -la

            # use the actions/setup-go@v5 action to set up Go
            - run: go version
            - uses: actions/setup-go@v5
              with:
                  go-version: '1.22'
            - run: go version\

            - name: build and test the go project
              run: |
                ls
                go build
                ls
                go test
                ./upper this should be convert into upper case
              working-directory: demo-files/upper
            
            
            - name: Execute python script
              run: |
                python --version
                python3 upper.py 'Testing This ouT'
              working-directory: demo-files/python

            