name: upper-build


on:
    push:
        paths:
            - '.github/workflows/upper-build.yml'
            - 'demo-files/upper/**'
    workflow_dispatch: # manual

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repository
              uses: actions/checkout@v4
            - run: go version
            